name: Debug LeetCode Secrets

on:
  workflow_dispatch:

jobs:
  debug:
    runs-on: ubuntu-latest
    steps:
      - name: Show available context keys
        run: |
          echo "Contexts: $(jq -r 'keys_unsorted[]' < <(echo '${{ toJson(github) }}'))"
      - name: Debug LEETCODE_CSRF_TOKEN
        run: |
          if [ -n "${{ secrets.LEETCODE_CSRF_TOKEN }}" ]; then
            echo "✅ LEETCODE_CSRF_TOKEN is set"
          else
            echo "❌ LEETCODE_CSRF_TOKEN is MISSING or empty"
            exit 1
          fi
      - name: Debug LEETCODE_SESSION
        run: |
          if [ -n "${{ secrets.LEETCODE_SESSION }}" ]; then
            echo "✅ LEETCODE_SESSION is set"
          else
            echo "❌ LEETCODE_SESSION is MISSING or empty"
            exit 1
          fi
