permissions:
  contents: write

name: Sync LeetCode Solutions
on:
  workflow_dispatch:
  schedule:
    - cron: "0 8 * * 6"

concurrency:
  group: leetcode-sync
  cancel-in-progress: true   # prevents multiple jobs from colliding

jobs:
  sync:
    if: github.actor != 'github-actions[bot]'  # stops the job from retriggering itself
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          persist-credentials: true   # keep token so push works

      - name: Sync LeetCode submissions
        uses: joshcai/leetcode-sync@v1.7
        with:
          github-token:        ${{ secrets.GITHUB_TOKEN }}
          leetcode-csrf-token: ${{ secrets.LEETCODE_CSRF_TOKEN }}
          leetcode-session:    ${{ secrets.LEETCODE_SESSION }}
          destination-folder:  ""
          filter-duplicate-secs: 86400
          commit-header:       "[LeetCode Sync]"
          verbose:             true
